# See https://github.com/FlyingPikachu/Quests/wiki/Configuration
accept-timeout: 20
allow-command-questing: true
allow-command-quests-with-npcs: false
allow-quitting: true
ask-confirmation: true
convert-data-on-startup: false
generate-files-on-join: true
ignore-locked-quests: false
kill-delay: 600
language: en-US
max-quests: 0
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: angry_villager
show-requirements: true
show-titles: true
translate-subcommands: false
use-compass: true
quester-blacklist:
- UUID
- UUID
- UUID